# Generated by Django 4.2.4 on 2023-08-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('postLikesDislikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikesdislikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
